=== TailrecIO/sbt-aws-fn/src/main/resources/sbt-aws-fun-1.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="timeout-type">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="300"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="memory-type">
        <xs:restriction base="xs:string">
            <xs:pattern value="192|256|320|384|448|512|576|640|704|768|832|896|960|1024|1088|1152|1216|1280|1344|1408|1472|1536" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="region-type">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value='collapse'/>
            <xs:enumeration value="ap-northeast-1"/>
            <xs:enumeration value="ap-northeast-2"/>
            <xs:enumeration value="ap-south-1"/>
            <xs:enumeration value="ap-southeast-1"/>
            <xs:enumeration value="ap-southeast-2"/>
            <xs:enumeration value="eu-central-1"/>
            <xs:enumeration value="eu-west-1"/>
            <xs:enumeration value="sa-east-1"/>
            <xs:enumeration value="us-east-1"/>
            <xs:enumeration value="us-west-1"/>
            <xs:enumeration value="us-west-2"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="regions-type">
        <xs:sequence>
            <xs:element name="region" type="region-type" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
<!-- Main Schema -->
    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="defaults">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="regions" type="regions-type" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="timeout" type="timeout-type" minOccurs="0" maxOccurs="1" />
                            <xs:element name="memory" type="memory-type" minOccurs="0" maxOccurs="1" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="artifacts">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="artifact">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:string" use="required" />
                                    <xs:attribute name="name" type="xs:string" />
                                    <xs:attribute name="minified" type="xs:boolean" default="true" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="functions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="function">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
                                        <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="artifact" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="handler" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="class" type="xs:string" minOccurs="1" maxOccurs="1" />
                                                    <xs:element name="method" type="xs:string" minOccurs="1" maxOccurs="1" />
                                                    <xs:element name="return-type" type="xs:string" minOccurs="0" maxOccurs="1" default="void" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <!-- These values are used for overriding default -->
                                        <xs:element name="regions" type="regions-type" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="timeout" type="timeout-type" minOccurs="0" maxOccurs="1" />
                                        <xs:element name="memory" type="memory-type" minOccurs="0" maxOccurs="1" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TailrecIO/sbt-aws-fn/config-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns="http://schema.tailrec.io/sbt-aws-fun"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://schema.tailrec.io/sbt-aws-fun http://www.tailrec.io/schema/sbt-aws-fun-1.0.xsd">
    <defaults>
        <regions>
            <region>us-west-1</region>
            <region>us-west-2</region>
            <region>us-west-2</region>
        </regions>
        <role>lambda_basic_execution</role>
        <memory>128</memory>
        <timeout>30</timeout>
    </defaults>
    <artifacts>
        <artifact id="image" minified="true" />
    </artifacts>
    <functions>
        <function>
            <name>img-resizer</name> 
            <artifact>image</artifact>
            <regions>
                <region>us-west-1</region>
            </regions>
            <role>lambda_basic_execution</role>
            <description>Create a thumbnail 36x36 when a new object is put in S3</description>
            <memory>192</memory>
            <timeout>10</timeout>
            <handler>
                <class>io.tailrec.lambda.ImageResizer</class>
                <method>resize</method>
                <return-type>void</return-type>
            </handler>
            <events>
                <http>
                    <api-name></api-name>
                    <resource-name></resource-name>
                    <method></method>
                    <deployment-stage></deployment-stage>
                    <security></security>
                </http>
            </events>
        </function>
    </functions>
</configuration>
